<?php

namespace App\Services\Stability;

class StabilitySurfaceRegistry
{
    public const TYPE_READ_PAGE = 'READ_PAGE';
    public const TYPE_DATATABLE = 'DATATABLE';
    public const TYPE_AJAX_READ = 'AJAX_READ';
    public const TYPE_WORKFLOW_WRITE = 'WORKFLOW_WRITE';
    public const TYPE_EXPORT = 'EXPORT';
    public const TYPE_ACCOUNTING_GATE = 'ACCOUNTING_GATE';

    /**
     * Return all release-critical registered surfaces.
     *
     * @return array<string, array{
     *     id: string,
     *     name: string,
     *     type: string,
     *     uri: string,
     *     method: string,
     *     auth: string,
     *     module: string|null,
     *     expected_status: int,
     *     expected_columns?: array<string>,
     *     params?: array<string, mixed>,
     *     repeat_critical?: bool
     * }>
     */
    public static function getSurfaces(): array
    {
        return [
            // ==========================================
            // 1. READ PAGES (Core Views)
            // ==========================================
            'page.dashboard' => [
                'id' => 'page.dashboard',
                'name' => 'Dashboard',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'dashboard',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'page.products.index' => [
                'id' => 'page.products.index',
                'name' => 'Products List Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'products',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'page.products.create' => [
                'id' => 'page.products.create',
                'name' => 'Add Product Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'products/create',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'page.sales.index' => [
                'id' => 'page.sales.index',
                'name' => 'Sales List Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'sales',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'page.sales.pos' => [
                'id' => 'page.sales.pos',
                'name' => 'Retail POS Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'pos',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'page.purchases.index' => [
                'id' => 'page.purchases.index',
                'name' => 'Purchases List Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'purchases',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'page.purchases.create' => [
                'id' => 'page.purchases.create',
                'name' => 'Add Purchase Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'purchases/create',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'page.returns.index' => [
                'id' => 'page.returns.index',
                'name' => 'Sale Returns List Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'return-sale',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'page.return-purchase.index' => [
                'id' => 'page.return-purchase.index',
                'name' => 'Purchase Returns List Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'return-purchase',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'page.transfers.index' => [
                'id' => 'page.transfers.index',
                'name' => 'Transfers List Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'transfers',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'page.expenses.index' => [
                'id' => 'page.expenses.index',
                'name' => 'Expenses List Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'expenses',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'page.incomes.index' => [
                'id' => 'page.incomes.index',
                'name' => 'Income List Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'incomes',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'page.customers.index' => [
                'id' => 'page.customers.index',
                'name' => 'Customers List Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'customer',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'page.suppliers.index' => [
                'id' => 'page.suppliers.index',
                'name' => 'Suppliers List Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'supplier',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'page.reports.tax' => [
                'id' => 'page.reports.tax',
                'name' => 'Generic Tax Report Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'report/tax-report',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'page.reports.sale' => [
                'id' => 'page.reports.sale',
                'name' => 'Sale Report Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'report/sale_report',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'page.reports.purchase' => [
                'id' => 'page.reports.purchase',
                'name' => 'Purchase Report Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'report/purchase',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'page.reports.stock' => [
                'id' => 'page.reports.stock',
                'name' => 'Stock Report Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'report/warehouse_stock',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'page.accounting.health' => [
                'id' => 'page.accounting.health',
                'name' => 'Accounting Health & Reconciliation Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'accounting/reconciliation',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'page.accounting.chart_of_accounts' => [
                'id' => 'page.accounting.chart_of_accounts',
                'name' => 'Accounting Chart of Accounts Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'accounting/chart-of-accounts',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'page.accounting.semantic_mappings' => [
                'id' => 'page.accounting.semantic_mappings',
                'name' => 'Accounting Semantic Mappings Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'accounting/semantic-account-mappings',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'page.accounting.inventory_close' => [
                'id' => 'page.accounting.inventory_close',
                'name' => 'Accounting Periodic Inventory Close Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'accounting/inventory-close',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'page.accounting.activation' => [
                'id' => 'page.accounting.activation',
                'name' => 'Accounting Activation Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'accounting/activation',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => [200, 302],
            ],

            // ==========================================
            // 2. SERVER-SIDE DATATABLES
            // ==========================================
            'datatable.sales' => [
                'id' => 'datatable.sales',
                'name' => 'Sales DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'sales/sale-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'expected_columns' => [
                    'key', 'options', 'date', 'reference_no', 'created_by', 'customer', 'warehouse_name',
                    'sale_status', 'payment_status', 'payment_method', 'currency', 'delivery_status',
                    'total_tax', 'order_tax', 'grand_total', 'returned_amount', 'paid_amount', 'due'
                ],
                'repeat_critical' => true,
            ],
            'datatable.purchases' => [
                'id' => 'datatable.purchases',
                'name' => 'Purchases DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'purchases/purchase-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'expected_columns' => [
                    'key', 'date', 'reference_no', 'supplier', 'purchase_status', 'grand_total',
                    'paid_amount', 'due', 'payment_status', 'options'
                ],
                'repeat_critical' => true,
            ],
            'datatable.products' => [
                'id' => 'datatable.products',
                'name' => 'Products DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'products/product-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'expected_columns' => [
                    'key', 'image', 'name', 'code', 'brand', 'category', 'qty', 'unit', 'price', 'cost', 'options'
                ],
                'repeat_critical' => true,
            ],
            'datatable.customers' => [
                'id' => 'datatable.customers',
                'name' => 'Customers DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'customers/customer-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'expected_columns' => [
                    'key', 'name', 'phone_number', 'email', 'customer_group', 'address', 'balance', 'options'
                ],
            ],
            'datatable.returns' => [
                'id' => 'datatable.returns',
                'name' => 'Sale Returns DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'return-sale/return-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'expected_columns' => [
                    'key', 'date', 'reference_no', 'biller', 'customer', 'warehouse', 'grand_total', 'options'
                ],
                'repeat_critical' => true,
            ],
            'datatable.return_purchases' => [
                'id' => 'datatable.return_purchases',
                'name' => 'Purchase Returns DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'return-purchase/return-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'expected_columns' => [
                    'key', 'date', 'reference_no', 'supplier', 'warehouse', 'grand_total', 'options'
                ],
                'repeat_critical' => true,
            ],
            'datatable.transfers' => [
                'id' => 'datatable.transfers',
                'name' => 'Transfers DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'transfers/transfer-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'expected_columns' => [
                    'key', 'date', 'reference_no', 'from_warehouse', 'to_warehouse', 'total_cost', 'total_tax', 'grand_total', 'status', 'options'
                ],
            ],
            'datatable.expenses' => [
                'id' => 'datatable.expenses',
                'name' => 'Expenses DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'expenses/expense-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'expected_columns' => [
                    'key', 'date', 'reference_no', 'warehouse', 'category', 'amount', 'tax', 'note', 'options'
                ],
                'repeat_critical' => true,
            ],
            'datatable.incomes' => [
                'id' => 'datatable.incomes',
                'name' => 'Incomes DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'incomes/income-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'expected_columns' => [
                    'key', 'date', 'reference_no', 'warehouse', 'category', 'amount', 'note', 'options'
                ],
            ],
            'datatable.reports.tax.sales' => [
                'id' => 'datatable.reports.tax.sales',
                'name' => 'Tax Report Sales DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/tax-report/output-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'expected_columns' => [
                    'date', 'reference_no', 'warehouse', 'contact', 'tax_name', 'tax_rate', 'taxable_amount', 'tax_amount', 'total_amount'
                ],
                'repeat_critical' => true,
            ],
            'datatable.reports.tax.purchases' => [
                'id' => 'datatable.reports.tax.purchases',
                'name' => 'Tax Report Purchases DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/tax-report/input-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'expected_columns' => [
                    'date', 'reference_no', 'warehouse', 'contact', 'tax_name', 'tax_rate', 'taxable_amount', 'tax_amount', 'total_amount'
                ],
                'repeat_critical' => true,
            ],
            'datatable.reports.tax.expenses' => [
                'id' => 'datatable.reports.tax.expenses',
                'name' => 'Tax Report Expenses DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/tax-report/expense-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'expected_columns' => [
                    'date', 'reference_no', 'warehouse', 'contact', 'tax_name', 'tax_rate', 'taxable_amount', 'tax_amount', 'total_amount'
                ],
                'repeat_critical' => true,
            ],

            // ==========================================
            // 3. AJAX ENDPOINTS (JSON Payloads)
            // ==========================================
            'ajax.recent_sale' => [
                'id' => 'ajax.recent_sale',
                'name' => 'Dashboard Recent Sales API',
                'type' => self::TYPE_AJAX_READ,
                'uri' => 'recent-sale',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'ajax.recent_purchase' => [
                'id' => 'ajax.recent_purchase',
                'name' => 'Dashboard Recent Purchases API',
                'type' => self::TYPE_AJAX_READ,
                'uri' => 'recent-purchase',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'ajax.pos.get_products' => [
                'id' => 'ajax.pos.get_products',
                'name' => 'POS Products API',
                'type' => self::TYPE_AJAX_READ,
                'uri' => 'sales/getproducts/{warehouse_id}/0/0',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
                'repeat_critical' => true,
            ],

            // ==========================================
            // 4. RESTAURANT MODULE SURFACES (When Enabled)
            // ==========================================
            'restaurant.page.pos' => [
                'id' => 'restaurant.page.pos',
                'name' => 'Restaurant POS Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'pos',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => 'restaurant',
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'restaurant.page.kds' => [
                'id' => 'restaurant.page.kds',
                'name' => 'Kitchen Display System (KDS)',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'restaurant/kitchen',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => 'restaurant',
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'restaurant.ajax.kds_data' => [
                'id' => 'restaurant.ajax.kds_data',
                'name' => 'Kitchen Dashboard Data AJAX',
                'type' => self::TYPE_AJAX_READ,
                'uri' => 'restaurant/kitchen/dashboard/data',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => 'restaurant',
                'expected_status' => 200,
                'repeat_critical' => true,
            ],
            'restaurant.page.floors' => [
                'id' => 'restaurant.page.floors',
                'name' => 'Restaurant Floors Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'restaurant/floor',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => 'restaurant',
                'expected_status' => 200,
            ],

            // ==========================================
            // 5. MANUFACTURING MODULE SURFACES (When Enabled)
            // ==========================================
            'manufacturing.page.recipes' => [
                'id' => 'manufacturing.page.recipes',
                'name' => 'Manufacturing Recipes List',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'manufacturing/recipes',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => 'manufacturing',
                'expected_status' => 200,
            ],
            'manufacturing.page.productions' => [
                'id' => 'manufacturing.page.productions',
                'name' => 'Manufacturing Productions List',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'manufacturing/productions',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => 'manufacturing',
                'expected_status' => 200,
            ],

            // ==========================================
            // 6. ADDITIONAL REPORTS DATATABLES
            // ==========================================
            'datatable.reports.supplier_purchases' => [
                'id' => 'datatable.reports.supplier_purchases',
                'name' => 'Supplier Purchases Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/supplier-purchase-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.supplier_payments' => [
                'id' => 'datatable.reports.supplier_payments',
                'name' => 'Supplier Payments Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/supplier-payment-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.supplier_returns' => [
                'id' => 'datatable.reports.supplier_returns',
                'name' => 'Supplier Returns Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/supplier-return-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.supplier_quotations' => [
                'id' => 'datatable.reports.supplier_quotations',
                'name' => 'Supplier Quotations Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/supplier-quotation-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.customer_due' => [
                'id' => 'datatable.reports.customer_due',
                'name' => 'Customer Due Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/customer-due-report-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.customer_sales' => [
                'id' => 'datatable.reports.customer_sales',
                'name' => 'Customer Sales Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/customer-sale-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.customer_payments' => [
                'id' => 'datatable.reports.customer_payments',
                'name' => 'Customer Payments Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/customer-payment-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.customer_quotations' => [
                'id' => 'datatable.reports.customer_quotations',
                'name' => 'Customer Quotations Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/customer-quotation-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.customer_returns' => [
                'id' => 'datatable.reports.customer_returns',
                'name' => 'Customer Returns Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/customer-return-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.barcodes' => [
                'id' => 'datatable.barcodes',
                'name' => 'Barcodes Catalog DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'barcodes/barcode-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'ajax.hrm.payroll' => [
                'id' => 'ajax.hrm.payroll',
                'name' => 'HRM Monthly Payroll Data API',
                'type' => self::TYPE_AJAX_READ,
                'uri' => 'payroll/monthly-data',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => 'hrm',
                'expected_status' => 200,
            ],
            'datatable.manufacturing.productions' => [
                'id' => 'datatable.manufacturing.productions',
                'name' => 'Manufacturing Productions DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'manufacturing/productions/production-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => 'manufacturing',
                'expected_status' => 200,
            ],
            'datatable.manufacturing.products' => [
                'id' => 'datatable.manufacturing.products',
                'name' => 'Manufacturing Products DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'manufacturing/products/product-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => 'manufacturing',
                'expected_status' => 200,
            ],
            'datatable.manufacturing.product_data' => [
                'id' => 'datatable.manufacturing.product_data',
                'name' => 'Manufacturing Product Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'manufacturing/product-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => 'manufacturing',
                'expected_status' => 200,
            ],
            'datatable.repair.services' => [
                'id' => 'datatable.repair.services',
                'name' => 'Repair Services DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'repair/service/service-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => 'repair',
                'expected_status' => 200,
            ],
            'datatable.restaurant.modifier_groups' => [
                'id' => 'datatable.restaurant.modifier_groups',
                'name' => 'Restaurant Modifier Groups DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'restaurant/modifier-group/data',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => 'restaurant',
                'expected_status' => 200,
            ],
            'datatable.reports.sale_report' => [
                'id' => 'datatable.reports.sale_report',
                'name' => 'Sale Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/sale_report_data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.purchase_report' => [
                'id' => 'datatable.reports.purchase_report',
                'name' => 'Purchase Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/purchase_report_data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.product_report' => [
                'id' => 'datatable.reports.product_report',
                'name' => 'Product Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/product_report_data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.stock_data' => [
                'id' => 'datatable.reports.stock_data',
                'name' => 'Stock Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/stock-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.warehouse_sale' => [
                'id' => 'datatable.reports.warehouse_sale',
                'name' => 'Warehouse Sale Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/warehouse-sale-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.warehouse_purchase' => [
                'id' => 'datatable.reports.warehouse_purchase',
                'name' => 'Warehouse Purchase Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/warehouse-purchase-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.warehouse_expense' => [
                'id' => 'datatable.reports.warehouse_expense',
                'name' => 'Warehouse Expense Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/warehouse-expense-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.warehouse_quotation' => [
                'id' => 'datatable.reports.warehouse_quotation',
                'name' => 'Warehouse Quotation Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/warehouse-quotation-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.warehouse_return' => [
                'id' => 'datatable.reports.warehouse_return',
                'name' => 'Warehouse Return Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/warehouse-return-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.user_sale' => [
                'id' => 'datatable.reports.user_sale',
                'name' => 'User Sale Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/user-sale-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.user_purchase' => [
                'id' => 'datatable.reports.user_purchase',
                'name' => 'User Purchase Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/user-purchase-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.user_expense' => [
                'id' => 'datatable.reports.user_expense',
                'name' => 'User Expense Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/user-expense-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.user_quotation' => [
                'id' => 'datatable.reports.user_quotation',
                'name' => 'User Quotation Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/user-quotation-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.user_payment' => [
                'id' => 'datatable.reports.user_payment',
                'name' => 'User Payment Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/user-payment-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.user_transfer' => [
                'id' => 'datatable.reports.user_transfer',
                'name' => 'User Transfer Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/user-transfer-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.user_payroll' => [
                'id' => 'datatable.reports.user_payroll',
                'name' => 'User Payroll Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/user-payroll-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.biller_sale' => [
                'id' => 'datatable.reports.biller_sale',
                'name' => 'Biller Sale Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/biller-sale-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.biller_quotation' => [
                'id' => 'datatable.reports.biller_quotation',
                'name' => 'Biller Quotation Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/biller-quotation-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.biller_payment' => [
                'id' => 'datatable.reports.biller_payment',
                'name' => 'Biller Payment Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/biller-payment-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.customer_group_sale' => [
                'id' => 'datatable.reports.customer_group_sale',
                'name' => 'Customer Group Sale Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/customer-group-sale-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.customer_group_payment' => [
                'id' => 'datatable.reports.customer_group_payment',
                'name' => 'Customer Group Payment Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/customer-group-payment-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.customer_group_quotation' => [
                'id' => 'datatable.reports.customer_group_quotation',
                'name' => 'Customer Group Quotation Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/customer-group-quotation-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.customer_group_return' => [
                'id' => 'datatable.reports.customer_group_return',
                'name' => 'Customer Group Return Report Data',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/customer-group-return-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.products.sale_history' => [
                'id' => 'datatable.products.sale_history',
                'name' => 'Product Sale History DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'products/sale-history-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.products.purchase_history' => [
                'id' => 'datatable.products.purchase_history',
                'name' => 'Product Purchase History DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'products/purchase-history-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.products.sale_return_history' => [
                'id' => 'datatable.products.sale_return_history',
                'name' => 'Product Sale Return History DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'products/sale-return-history-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.products.purchase_return_history' => [
                'id' => 'datatable.products.purchase_return_history',
                'name' => 'Product Purchase Return History DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'products/purchase-return-history-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.products.adjustment_history' => [
                'id' => 'datatable.products.adjustment_history',
                'name' => 'Product Adjustment History DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'products/adjustment-history-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.products.transfer_history' => [
                'id' => 'datatable.products.transfer_history',
                'name' => 'Product Transfer History DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'products/transfer-history-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.categories' => [
                'id' => 'datatable.categories',
                'name' => 'Category DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'category/category-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.warehouses' => [
                'id' => 'datatable.warehouses',
                'name' => 'Warehouses DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'warehouse-data',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'page.sales.deleted' => [
                'id' => 'page.sales.deleted',
                'name' => 'Deleted Sales Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'sales/deleted_data',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.packing_slips' => [
                'id' => 'datatable.packing_slips',
                'name' => 'Packing Slips DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'packing-slips/packing-slip-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.challans' => [
                'id' => 'datatable.challans',
                'name' => 'Challans DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'challans/challan-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.deliveries' => [
                'id' => 'datatable.deliveries',
                'name' => 'Deliveries DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'delivery/delivery_list_data',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.quotations' => [
                'id' => 'datatable.quotations',
                'name' => 'Quotations DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'quotations/quotation-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'page.purchases.deleted' => [
                'id' => 'page.purchases.deleted',
                'name' => 'Deleted Purchases Screen',
                'type' => self::TYPE_READ_PAGE,
                'uri' => 'purchases/deleted_data',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.exchanges' => [
                'id' => 'datatable.exchanges',
                'name' => 'Exchanges DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'exchange/exchange-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.daily_sale_objective' => [
                'id' => 'datatable.reports.daily_sale_objective',
                'name' => 'Daily Sale Objective Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/daily-sale-objective-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.profitability.product' => [
                'id' => 'datatable.reports.profitability.product',
                'name' => 'Profitability Product Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/profitability/product-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.profitability.category' => [
                'id' => 'datatable.reports.profitability.category',
                'name' => 'Profitability Category Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/profitability/category-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.profitability.brand' => [
                'id' => 'datatable.reports.profitability.brand',
                'name' => 'Profitability Brand Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/profitability/brand-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.profitability.customer' => [
                'id' => 'datatable.reports.profitability.customer',
                'name' => 'Profitability Customer Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/profitability/customer-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.profitability.location' => [
                'id' => 'datatable.reports.profitability.location',
                'name' => 'Profitability Location Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/profitability/location-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
            'datatable.reports.profitability.invoice' => [
                'id' => 'datatable.reports.profitability.invoice',
                'name' => 'Profitability Invoice Report DataTable',
                'type' => self::TYPE_DATATABLE,
                'uri' => 'report/profitability/invoice-data',
                'method' => 'POST',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],

            // ==========================================
            // 7. EXPORTS
            // ==========================================
            'export.reports.tax.pdf' => [
                'id' => 'export.reports.tax.pdf',
                'name' => 'Tax Report Export',
                'type' => self::TYPE_EXPORT,
                'uri' => 'report/tax-report/export',
                'method' => 'GET',
                'auth' => 'admin',
                'module' => null,
                'expected_status' => 200,
            ],
        ];
    }
}
