<?php
use Illuminate\Support\Facades\Route;
use Modules\Construction\Http\Controllers\DashboardController;
use Modules\Construction\Http\Controllers\OperationsController;
use Modules\Construction\Http\Controllers\ReportController;
use Modules\Construction\Http\Controllers\ProcurementController;
use Modules\Construction\Http\Controllers\WorkforceController;
use Modules\Construction\Http\Controllers\FinanceController;

Route::middleware(['common','auth','active','warehouse.access','module.access:construction'])->prefix('construction')->name('construction.')->group(function(){
 Route::get('dashboard',DashboardController::class)->middleware('permission:construction.dashboard.view')->name('dashboard');
 Route::get('clients',[OperationsController::class,'clients'])->name('clients'); Route::post('clients',[OperationsController::class,'storeClient'])->name('clients.store');
 Route::get('material-catalog',[OperationsController::class,'materialCatalog'])->name('catalog'); Route::post('material-catalog',[OperationsController::class,'storeMaterial'])->name('catalog.store');
 Route::middleware('permission:construction.project-costs.manage')->group(function(){Route::get('project-costs',[OperationsController::class,'costs'])->name('costs');Route::post('project-costs',[OperationsController::class,'storeCost'])->name('costs.store');Route::post('project-costs/{cost}/post',[OperationsController::class,'postCost'])->name('costs.post');});
 Route::get('materials',[OperationsController::class,'materials'])->middleware('permission:construction.material-issues.manage')->name('materials'); Route::post('material-issues',[OperationsController::class,'storeIssue'])->middleware('permission:construction.material-issues.manage')->name('issues.store'); Route::post('material-issues/{issue}/approve',[OperationsController::class,'approveIssue'])->middleware('permission:construction.material-issues.manage')->name('issues.approve'); Route::post('material-issues/{issue}/reject',[OperationsController::class,'rejectIssue'])->middleware('permission:construction.material-issues.manage')->name('issues.reject'); Route::post('material-issues/{issue}/returns',[OperationsController::class,'storeReturn'])->middleware('permission:construction.material-returns.manage')->name('returns.store');
 Route::middleware('permission:construction.subcontractors.manage')->group(function(){Route::get('subcontractors',[OperationsController::class,'subcontractors'])->name('subcontractors');Route::post('subcontractors',[OperationsController::class,'storeSubcontractor'])->name('subcontractors.store');Route::post('subcontractor-contracts',[OperationsController::class,'storeContract'])->name('contracts.store');Route::post('subcontractor-payments',[OperationsController::class,'storeSubcontractorPayment'])->name('subcontractor-payments.store');});
 Route::middleware('permission:construction.project-wages.manage')->group(function(){Route::get('workforce',[WorkforceController::class,'index'])->name('workforce');Route::post('project-wages',[WorkforceController::class,'storeWage'])->name('wages.store');Route::post('employee-rewards',[WorkforceController::class,'storeReward'])->name('employee-rewards.store');Route::post('employee-expenses',[WorkforceController::class,'storeExpense'])->name('employee-expenses.store');Route::post('employee-advances',[WorkforceController::class,'storeAdvance'])->name('employee-advances.store');Route::post('employee-advances/{advance}/settlements',[WorkforceController::class,'settleAdvance'])->name('employee-advances.settle');});
 Route::middleware('permission:construction.equipment.manage')->group(function(){Route::get('equipment',[OperationsController::class,'equipment'])->name('equipment');Route::post('equipment',[OperationsController::class,'storeEquipment'])->name('equipment.store');Route::post('equipment-assignments',[OperationsController::class,'storeAssignment'])->name('assignments.store');Route::post('equipment/{equipment}/lifecycle',[OperationsController::class,'updateEquipment'])->name('equipment.lifecycle');Route::post('fixed-assets',[OperationsController::class,'storeFixedAsset'])->name('fixed-assets.store');});
 Route::middleware('permission:construction.project-receipts.manage')->group(function(){Route::get('project-receipts',[OperationsController::class,'receipts'])->name('receipts');Route::post('project-receipts',[OperationsController::class,'storeReceipt'])->name('receipts.store');Route::post('project-receipts/{receipt}/post',[OperationsController::class,'postReceipt'])->name('receipts.post');});
 Route::middleware('permission:construction.shareholders.manage')->group(function(){Route::get('shareholders',[FinanceController::class,'shareholders'])->name('shareholders');Route::post('shareholders',[FinanceController::class,'storeShareholder'])->name('shareholders.store');Route::post('shareholder-transactions',[FinanceController::class,'storeShareholderTransaction'])->name('shareholder-transactions.store');});
 Route::middleware('permission:construction.procurement.view')->group(function(){Route::get('procurement-logistics',[ProcurementController::class,'index'])->name('procurement');});
 Route::post('transport-records',[ProcurementController::class,'storeTransport'])->middleware('permission:construction.transport.manage')->name('transport.store');
 Route::post('supplier-items',[ProcurementController::class,'storeSupplierItem'])->middleware('permission:construction.supplier-items.manage')->name('supplier-items.store');
 Route::middleware('permission:construction.reports.view')->group(function(){Route::get('reports/project-profitability',[ReportController::class,'profitability'])->name('reports.profitability');Route::get('reports/project-statement',[ReportController::class,'statement'])->name('reports.statement');Route::get('reports/payments-due',[FinanceController::class,'paymentsDue'])->name('reports.payments-due');Route::get('reports/other-revenue',[FinanceController::class,'otherRevenue'])->name('reports.other-revenue');Route::get('reports/inventory-value',[FinanceController::class,'inventoryValue'])->name('reports.inventory-value');Route::get('reports/stock-movement',[ReportController::class,'stockMovement'])->name('reports.stock-movement');Route::get('reports/accounts-cash-movement',[ReportController::class,'accountsCashMovement'])->name('reports.accounts-cash-movement');});
 Route::get('settings',[OperationsController::class,'settings'])->name('settings');
});
