@extends('backend.layout.main')
@section('construction-title','Accounts & Cash Movement Report')
@section('content')
<div class="container-fluid">@include('construction::partials.header')
<div class="alert alert-light border">Posted double-entry journal lines from SalePro accounting. Project/site/category filters use the dimensions already stamped on authoritative journal lines.</div>
<form class="construction-form" method="get"><div class="row align-items-end"><div class="col-md-2"><label>From</label><input type="date" class="form-control" name="start_date" value="{{$startDate}}"></div><div class="col-md-2"><label>To</label><input type="date" class="form-control" name="end_date" value="{{$endDate}}"></div><div class="col-md-3"><label>Project</label><select class="form-control" name="project_id"><option value="">All projects</option>@foreach($projects as $p)<option value="{{$p->id}}" @selected($projectId==$p->id)>{{$p->title}}</option>@endforeach</select></div><div class="col-md-3"><label>Related party contains</label><input class="form-control" name="party" value="{{$party}}" placeholder="Supplier / client / employee / shareholder"></div><div class="col-md-2"><button class="btn btn-primary btn-block">Filter</button></div></div></form>
<div class="construction-grid mb-4"><div class="card construction-kpi"><div class="card-body"><small>Journal Lines</small><div class="value">{{$summary['journal_lines']}}</div></div></div><div class="card construction-kpi"><div class="card-body"><small>Total Debits</small><div class="value">{{number_format($summary['debit'],2)}}</div></div></div><div class="card construction-kpi"><div class="card-body"><small>Total Credits</small><div class="value">{{number_format($summary['credit'],2)}}</div></div></div><div class="card construction-kpi"><div class="card-body"><small>Cash/Bank In</small><div class="value">{{number_format($summary['cash_bank_in'],2)}}</div></div></div><div class="card construction-kpi"><div class="card-body"><small>Cash/Bank Out</small><div class="value">{{number_format($summary['cash_bank_out'],2)}}</div></div></div></div>
<div class="construction-table table-responsive"><table class="table table-bordered table-sm"><thead><tr><th>Date</th><th>Reference</th><th>Event</th><th>Related Party</th><th>Project / Site</th><th>Account</th><th>Description</th><th class="text-right">Debit</th><th class="text-right">Credit</th></tr></thead><tbody>@forelse($rows as $r)<tr><td>{{$r->entry_date}}</td><td>{{$r->reference_no}}</td><td>{{ucwords(str_replace('_',' ',$r->event_type))}}</td><td>{{$r->party ?: '—'}}</td><td>{{$r->project_name ?: '—'}}@if($r->site_name)<br><small>{{$r->site_name}}</small>@endif</td><td>{{$r->account_code}} · {{$r->account_name}}</td><td>{{$r->description ?: $r->note}}</td><td class="text-right">{{number_format($r->debit,2)}}</td><td class="text-right">{{number_format($r->credit,2)}}</td></tr>@empty<tr><td colspan="9" class="text-center">No matching accounting movements.</td></tr>@endforelse</tbody></table></div>
</div>
@endsection
