@extends('backend.layout.main')
@section('construction-title','Construction Stock Movement Report')
@section('content')
<div class="container-fluid">@include('construction::partials.header')
<form class="construction-form" method="get"><div class="row align-items-end">
<div class="col-md-2"><label>From</label><input type="date" class="form-control" name="start_date" value="{{$startDate}}"></div>
<div class="col-md-2"><label>To</label><input type="date" class="form-control" name="end_date" value="{{$endDate}}"></div>
<div class="col-md-3"><label>Project</label><select class="form-control" name="project_id"><option value="">All projects</option>@foreach($projects as $p)<option value="{{$p->id}}" @selected($projectId==$p->id)>{{$p->title}}</option>@endforeach</select></div>
<div class="col-md-3"><label>Warehouse</label><select class="form-control" name="warehouse_id"><option value="">All warehouses</option>@foreach($warehouses as $w)<option value="{{$w->id}}" @selected($warehouseId==$w->id)>{{$w->name}}</option>@endforeach</select></div>
<div class="col-md-2"><button class="btn btn-primary btn-block">Filter</button></div></div></form>
<div class="construction-grid mb-4"><div class="card construction-kpi"><div class="card-body"><small>Movements</small><div class="value">{{$summary['movement_count']}}</div></div></div><div class="card construction-kpi"><div class="card-body"><small>Qty In</small><div class="value">{{number_format($summary['qty_in'],4)}}</div></div></div><div class="card construction-kpi"><div class="card-body"><small>Qty Out</small><div class="value">{{number_format($summary['qty_out'],4)}}</div></div></div><div class="card construction-kpi"><div class="card-body"><small>Pending Receipt Qty</small><div class="value">{{number_format($summary['pending_qty'],4)}}</div></div></div></div>
<div class="construction-table table-responsive mb-4"><h4>Posted Stock Movements</h4><table class="table table-bordered table-sm"><thead><tr><th>Date</th><th>Type</th><th>Reference</th><th>Project</th><th>Warehouse</th><th>Product</th><th class="text-right">In</th><th class="text-right">Out</th><th class="text-right">Balance</th></tr></thead><tbody>@forelse($movements as $r)<tr><td>{{substr($r['movement_at'],0,10)}}</td><td>{{ucwords(str_replace('_',' ',$r['source_type']))}}</td><td>{{$r['reference_no']}}</td><td>{{$r['project_name'] ?: '—'}}</td><td>{{$r['warehouse_name']}}</td><td>{{$r['product_code']}} · {{$r['product_name']}}</td><td class="text-right">{{number_format($r['qty_in'],4)}}</td><td class="text-right">{{number_format($r['qty_out'],4)}}</td><td class="text-right">{{number_format($r['running_balance'],4)}}</td></tr>@empty<tr><td colspan="9" class="text-center">No matching stock movements.</td></tr>@endforelse</tbody></table></div>
<div class="construction-table table-responsive"><h4>Pending / Not-Received Purchases</h4><p class="text-muted">These quantities are obligations in transit and are intentionally not posted as stock until received.</p><table class="table table-bordered table-sm"><thead><tr><th>Date</th><th>Reference</th><th>Project</th><th>Warehouse</th><th>Product</th><th class="text-right">Ordered</th><th class="text-right">Received</th><th class="text-right">Pending</th></tr></thead><tbody>@forelse($pending as $r)<tr><td>{{substr($r->created_at,0,10)}}</td><td>{{$r->reference_no}}</td><td>{{$r->project_name ?: '—'}}</td><td>{{$r->warehouse_name}}</td><td>{{$r->product_code}} · {{$r->product_name}}</td><td class="text-right">{{number_format($r->qty,4)}}</td><td class="text-right">{{number_format($r->recieved,4)}}</td><td class="text-right"><strong>{{number_format(max(0,$r->qty-$r->recieved),4)}}</strong></td></tr>@empty<tr><td colspan="8" class="text-center">No pending purchase receipts.</td></tr>@endforelse</tbody></table></div>
</div>
@endsection
