@extends('backend.layout.main') @section('construction-title','Project Costs')
@section('content')<div class="container-fluid">@include('construction::partials.header') @include('construction::partials.messages')
<form class="construction-form" method="post" action="{{ route('construction.costs.store') }}">@csrf <h4>Record Direct Project Cost</h4><div class="row">
<div class="col-md-3 form-group"><label>Project</label><select name="project_id" class="form-control" required>@foreach($projects as $p)<option value="{{$p->id}}">{{$p->project_code}} {{$p->title}}</option>@endforeach</select></div>
<div class="col-md-2 form-group"><label>Category</label><select name="cost_category_id" class="form-control" required>@foreach($categories as $c)<option value="{{$c->id}}">{{$c->name}}</option>@endforeach</select></div>
<div class="col-md-2 form-group"><label>Supplier</label><select name="supplier_id" class="form-control"><option value="">—</option>@foreach($suppliers as $s)<option value="{{$s->id}}">{{$s->name}}</option>@endforeach</select></div>
<div class="col-md-2 form-group"><label>Date</label><input type="date" name="date" value="{{date('Y-m-d')}}" class="form-control" required></div><div class="col-md-2 form-group"><label>Amount</label><input type="number" step=".0001" min=".0001" name="amount" class="form-control" required></div>
<div class="col-md-8 form-group"><label>Description</label><input name="description" class="form-control" required></div><div class="col-md-3 form-group"><label>Reference</label><input name="reference" class="form-control"></div><div class="col-md-1 form-group d-flex align-items-end"><button class="btn btn-primary">Save</button></div></div></form>
<div class="construction-table table-responsive"><table class="table"><thead><tr><th>Date</th><th>Project</th><th>Category</th><th>Description</th><th>Reference</th><th class="text-right">Amount</th></tr></thead><tbody>@foreach($costs as $cost)<tr><td>{{$cost->date->format('Y-m-d')}}</td><td>{{$cost->project->title}}</td><td>{{$cost->category->name}}</td><td>{{$cost->description}}</td><td>{{$cost->reference}}</td><td class="text-right">{{number_format($cost->amount,2)}}</td></tr>@endforeach</tbody></table>{{$costs->links()}}</div></div>@endsection
