@extends('backend.layout.main')
@section('construction-title','Construction Dashboard')
@section('content')
<div class="container-fluid">@include('construction::partials.header')
<div class="construction-grid mb-4">
@foreach(['active_projects'=>'Active Projects','contract_value'=>'Contract Value','budget'=>'Project Budget','current_cost'=>'Current Project Costs','receipts'=>'Project Receipts / Advances','remaining_contract'=>'Remaining Contract Amount (not A/R)','projected_profit'=>'Projected Contract Profit','supplier_payables'=>'Supplier Dues','subcontract_dues'=>'Subcontractor Dues','materials_value'=>'Materials in Stores','labour_cost'=>'Labour Cost','employee_advances'=>'Outstanding Employee Advances','equipment_assigned'=>'Equipment Assigned','pending_receipts'=>'Pending / Not-Received Material Lines'] as $key=>$label)
<div class="card construction-kpi"><div class="card-body"><div class="text-muted small">{{ $label }}</div><div class="value">{{ in_array($key,['active_projects','equipment_assigned','pending_receipts']) ? number_format($kpis[$key]) : number_format($kpis[$key],2) }}</div></div></div>
@endforeach
</div>
<div class="row"><div class="col-lg-7"><div class="construction-table"><h4>Recent Projects</h4><div class="table-responsive"><table class="table"><thead><tr><th>Code / Project</th><th>Client</th><th>Status</th><th>Cost</th><th>Remaining Contract</th></tr></thead><tbody>@forelse($projects as $project)<tr><td><strong>{{ $project->project_code ?: '—' }}</strong><br>{{ $project->title }}</td><td>{{ optional($project->customer)->name ?: '—' }}</td><td>{{ ucfirst($project->project_status) }}</td><td>{{ number_format($summaries[$project->id]['total'],2) }}</td><td>{{ number_format($summaries[$project->id]['receivable'],2) }}</td></tr>@empty<tr><td colspan="5">No projects yet.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="col-lg-5"><div class="construction-table mb-3"><h4>Recent Material Issues</h4>@forelse($recentIssues as $issue)<div class="border-bottom py-2"><strong>{{ $issue->reference_no }}</strong><span class="float-right">{{ $issue->issue_date }}</span><div class="text-muted">{{ $issue->project_name }}</div></div>@empty<p class="text-muted">No material issues.</p>@endforelse</div><div class="construction-table"><h4>Equipment Currently Assigned</h4>@forelse($equipment as $item)<div class="border-bottom py-2"><strong>{{ $item->code }} · {{ $item->name }}</strong><div class="text-muted">{{ $item->project_name }} since {{ $item->assigned_from }}</div></div>@empty<p class="text-muted">No active assignments.</p>@endforelse</div></div></div>
</div>
@endsection
