@extends('backend.layout.main')
@section('construction-title','Material Issues & Returns')
@section('content')
<div class="container-fluid">
@include('construction::partials.header') @include('construction::partials.messages')
<div class="alert alert-info">Material issue permits now use an approval lifecycle. Creating a request does <strong>not</strong> move stock. Authoritative SalePro stock is reduced only when the request is approved.</div>
<form class="construction-form" method="post" action="{{route('construction.issues.store')}}">@csrf
<h4>New Material Issue / Disbursement Permit</h4>
<div class="row"><div class="col-md-4 form-group"><label>Project</label><select class="form-control" name="project_id" required>@foreach($projects as $p)<option value="{{$p->id}}">{{$p->project_code}} {{$p->title}}</option>@endforeach</select></div><div class="col-md-4 form-group"><label>Store / Site Store</label><select class="form-control" name="warehouse_id" required>@foreach($warehouses as $w)<option value="{{$w->id}}">{{$w->name}}</option>@endforeach</select></div><div class="col-md-3 form-group"><label>Issue Date</label><input type="date" name="issue_date" value="{{date('Y-m-d')}}" class="form-control" required></div></div>
<div id="issue-lines"><div class="row issue-line"><div class="col-md-7 form-group"><label>Material stock row</label><select name="stock_row_id[]" class="form-control" required>@foreach($stock as $s)<option value="{{$s->id}}">{{$s->warehouse->name}} · {{$s->product->code}} · {{$s->product->name}} (available {{number_format($s->qty,4)}})</option>@endforeach</select></div><div class="col-md-2 form-group"><label>Quantity</label><input name="quantity[]" type="number" step=".0001" min=".0001" class="form-control" required></div><div class="col-md-3 form-group"><label>Cost Category</label><select name="cost_category_id[]" class="form-control"><option value="">Materials</option>@foreach($categories as $c)<option value="{{$c->id}}">{{$c->name}}</option>@endforeach</select></div></div></div>
<div class="form-group"><label>Notes</label><input name="notes" class="form-control"></div><button type="button" id="add-issue-line" class="btn btn-outline-secondary">Add Material</button> <button class="btn btn-primary">Submit for Approval</button></form>
<div class="construction-table"><h4>Material Issue Permits</h4>
@forelse($issues as $issue)
<div class="card mb-3"><div class="card-header"><strong>{{$issue->reference_no}}</strong> · {{$issue->project->title}} · {{$issue->warehouse->name}} · <span class="badge {{$issue->status==='issued'?'badge-success':($issue->status==='pending'?'badge-warning':'badge-secondary')}}">{{ucfirst($issue->status)}}</span><span class="float-right">{{$issue->issue_date->format('Y-m-d')}}</span></div>
<div class="card-body"><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Material</th><th>Requested/Issued</th><th>Unit Cost</th><th>Total</th></tr></thead><tbody>@foreach($issue->items as $item)<tr><td>{{$item->product->code}} · {{$item->product->name}}</td><td>{{number_format($item->quantity,4)}}</td><td>{{number_format($item->unit_cost,4)}}</td><td>{{number_format($item->total_cost,4)}}</td></tr>@endforeach</tbody></table></div>
@if($issue->status==='pending')<div class="row"><div class="col-md-2"><form method="post" action="{{route('construction.issues.approve',$issue)}}">@csrf<button class="btn btn-success btn-block">Approve & Issue</button></form></div><div class="col-md-10"><form method="post" action="{{route('construction.issues.reject',$issue)}}" class="form-inline">@csrf<input name="rejection_reason" class="form-control mr-2 flex-grow-1" placeholder="Rejection reason (optional)"><button class="btn btn-outline-danger">Reject</button></form></div></div>
@elseif($issue->status==='issued')<form method="post" action="{{route('construction.returns.store',$issue)}}">@csrf<div class="table-responsive mt-3"><table class="table table-sm"><thead><tr><th>Material</th><th>Issued</th><th>Return Qty</th></tr></thead><tbody>@foreach($issue->items as $item)<tr><td>{{$item->product->code}} · {{$item->product->name}}</td><td>{{number_format($item->quantity,4)}}</td><td><input class="form-control form-control-sm" type="number" step=".0001" min="0" max="{{$item->quantity}}" name="quantity[{{$item->id}}]" value="0"></td></tr>@endforeach</tbody></table></div><div class="row"><div class="col-md-3"><input type="date" name="return_date" value="{{date('Y-m-d')}}" class="form-control" required></div><div class="col-md-7"><input name="notes" class="form-control" placeholder="Return notes"></div><div class="col-md-2"><button class="btn btn-outline-primary btn-block">Post Return</button></div></div></form>
@elseif($issue->rejection_reason)<div class="text-danger">Reason: {{$issue->rejection_reason}}</div>@endif
</div></div>
@empty<p>No material issues yet.</p>@endforelse {{$issues->links()}}</div></div>
<script>document.addEventListener('DOMContentLoaded',function(){document.getElementById('add-issue-line').addEventListener('click',function(){var row=document.querySelector('.issue-line').cloneNode(true);row.querySelectorAll('input').forEach(function(i){i.value=''});document.getElementById('issue-lines').appendChild(row)})})</script>
@endsection
