@extends('backend.layout.main')
@section('construction-title','Project Workforce & Employee Finance')
@section('content')
<div class="container-fluid">
@include('construction::partials.header') @include('construction::partials.messages')

<div class="construction-form">
<h4>Labour Report Filters</h4>
<form method="get" action="{{route('construction.workforce')}}"><div class="row">
<div class="col-md-3 form-group"><label>Project</label><select name="project_id" class="form-control"><option value="">All projects</option>@foreach($projects as $p)<option value="{{$p->id}}" @selected(($filters['project_id']??'')==$p->id)>{{$p->title}}</option>@endforeach</select></div>
<div class="col-md-3 form-group"><label>Employee</label><select name="employee_id" class="form-control"><option value="">All employees</option>@foreach($employees as $e)<option value="{{$e->id}}" @selected(($filters['employee_id']??'')==$e->id)>{{$e->name}}</option>@endforeach</select></div>
<div class="col-md-2 form-group"><label>From</label><input type="date" name="from" value="{{$filters['from']??''}}" class="form-control"></div>
<div class="col-md-2 form-group"><label>To</label><input type="date" name="to" value="{{$filters['to']??''}}" class="form-control"></div>
<div class="col-md-2 form-group d-flex align-items-end"><button class="btn btn-secondary mr-2">Filter</button><a href="{{route('construction.workforce')}}" class="btn btn-light">Reset</a></div>
</div></form>
<div class="row"><div class="col-md-6"><h6>Employee-wise Labour Cost</h6><table class="table table-sm"><thead><tr><th>Employee</th><th class="text-right">Cost</th></tr></thead><tbody>@foreach($labourByEmployee as $r)<tr><td>{{$r->employee->name??'Employee #'.$r->employee_id}}</td><td class="text-right">{{number_format($r->total,2)}}</td></tr>@endforeach</tbody></table></div><div class="col-md-6"><h6>Project-wise Labour Cost</h6><table class="table table-sm"><thead><tr><th>Project</th><th class="text-right">Cost</th></tr></thead><tbody>@foreach($labourByProject as $r)<tr><td>{{$r->project->title??'Project #'.$r->project_id}}</td><td class="text-right">{{number_format($r->total,2)}}</td></tr>@endforeach</tbody></table></div></div>
</div>

<div class="construction-form"><h4>Monthly Employee / Project Work Record</h4><p class="text-muted">This is the project labour allocation record. It does not create a second payroll accounting entry; SalePro Payroll remains authoritative for salary payment.</p>
<form method="post" action="{{route('construction.wages.store')}}">@csrf<div class="row">
<div class="col-md-3 form-group"><label>Project</label><select name="project_id" class="form-control" required>@foreach($projects as $p)<option value="{{$p->id}}">{{$p->title}}</option>@endforeach</select></div>
<div class="col-md-3 form-group"><label>Site</label><select name="site_id" class="form-control"><option value="">General project</option>@foreach($sites as $s)<option value="{{$s->id}}">{{$s->name}}</option>@endforeach</select></div>
<div class="col-md-3 form-group"><label>Employee</label><select name="employee_id" class="form-control" required>@foreach($employees as $e)<option value="{{$e->id}}">{{$e->name}}</option>@endforeach</select></div>
<div class="col-md-3 form-group"><label>Period</label><input type="date" name="period" value="{{date('Y-m-01')}}" class="form-control" required></div>
<div class="col-md-2 form-group"><label>Days Worked</label><input type="number" step=".5" name="days_worked" class="form-control"></div>
<div class="col-md-2 form-group"><label>Rate</label><input type="number" step=".0001" name="rate" class="form-control"></div>
<div class="col-md-2 form-group"><label>Rate Basis</label><select name="rate_basis" class="form-control"><option value="daily">Daily</option><option value="monthly">Monthly</option><option value="fixed">Fixed Allocation</option></select></div>
<div class="col-md-2 form-group"><label>Salary/Wage Allocation</label><input type="number" step=".0001" name="basic_amount" class="form-control" required></div>
<div class="col-md-2 form-group"><label>Overtime</label><input type="number" step=".0001" name="overtime_amount" value="0" class="form-control"></div>
<div class="col-md-2 form-group"><label>Additional / Bonus</label><input type="number" step=".0001" name="bonus_amount" value="0" class="form-control"></div>
<div class="col-md-2 form-group"><label>Deduction</label><input type="number" step=".0001" name="deduction_amount" value="0" class="form-control"></div>
<div class="col-md-3 form-group"><label>Cost Category</label><select name="cost_category_id" class="form-control"><option value="">Labour</option>@foreach($categories as $c)<option value="{{$c->id}}">{{$c->name}}</option>@endforeach</select></div>
<div class="col-md-5 form-group"><label>Notes</label><input name="notes" class="form-control"></div><div class="col-md-2 form-group d-flex align-items-end"><button class="btn btn-primary">Record Allocation</button></div>
</div></form></div>

<div class="construction-table table-responsive mb-4"><table class="table"><thead><tr><th>Period</th><th>Project</th><th>Employee</th><th>Days</th><th>Rate</th><th>Basis</th><th>Allocation</th><th>Overtime</th><th>Additional</th><th>Deduction</th><th>Total</th></tr></thead><tbody>@foreach($wages as $w)<tr><td>{{$w->period->format('Y-m-d')}}</td><td>{{$w->project->title}}</td><td>{{$w->employee->name}}</td><td>{{$w->days_worked}}</td><td>{{number_format((float)$w->rate,2)}}</td><td>{{$w->rate_basis}}</td><td>{{number_format($w->basic_amount,2)}}</td><td>{{number_format($w->overtime_amount,2)}}</td><td>{{number_format($w->bonus_amount,2)}}</td><td>{{number_format($w->deduction_amount,2)}}</td><td><strong>{{number_format($w->total_amount,2)}}</strong></td></tr>@endforeach</tbody></table>{{$wages->links()}}</div>

<div class="row">
<div class="col-lg-6"><div class="construction-form"><h4>Employee Reward</h4><form method="post" action="{{route('construction.employee-rewards.store')}}">@csrf<div class="row">
<div class="col-md-6 form-group"><label>Employee</label><select name="employee_id" class="form-control" required>@foreach($employees as $e)<option value="{{$e->id}}">{{$e->name}}</option>@endforeach</select></div><div class="col-md-6 form-group"><label>Project (optional)</label><select name="project_id" class="form-control"><option value="">Company-wide</option>@foreach($projects as $p)<option value="{{$p->id}}">{{$p->title}}</option>@endforeach</select></div>
<div class="col-md-4 form-group"><label>Date</label><input type="date" name="reward_date" value="{{date('Y-m-d')}}" class="form-control" required></div><div class="col-md-4 form-group"><label>Type</label><select name="reward_type" class="form-control"><option value="bonus">Bonus</option><option value="incentive">Incentive</option><option value="reward">Reward</option></select></div><div class="col-md-4 form-group"><label>Amount</label><input type="number" step=".0001" name="amount" class="form-control" required></div>
<div class="col-md-4 form-group"><label>Status</label><select name="status" class="form-control"><option value="approved">Approved</option><option value="pending">Pending</option><option value="cancelled">Cancelled</option></select></div><div class="col-md-4 form-group"><label>Reference</label><input name="reference" class="form-control"></div><div class="col-md-4 form-group"><label>Notes</label><input name="notes" class="form-control"></div><div class="col-12"><button class="btn btn-primary">Save Reward</button></div>
</div></form></div></div>
<div class="col-lg-6"><div class="construction-form"><h4>Employee Project Expense</h4><p class="text-muted">Creates a linked SalePro Expense and accounting entry.</p><form method="post" action="{{route('construction.employee-expenses.store')}}">@csrf<div class="row">
<div class="col-md-6 form-group"><label>Employee</label><select name="employee_id" class="form-control" required>@foreach($employees as $e)<option value="{{$e->id}}">{{$e->name}}</option>@endforeach</select></div><div class="col-md-6 form-group"><label>Project</label><select name="project_id" class="form-control"><option value="">General company</option>@foreach($projects as $p)<option value="{{$p->id}}">{{$p->title}}</option>@endforeach</select></div>
<div class="col-md-4 form-group"><label>Date</label><input type="date" name="expense_date" value="{{date('Y-m-d')}}" class="form-control" required></div><div class="col-md-4 form-group"><label>Category</label><select name="cost_category_id" class="form-control" required>@foreach($categories as $c)<option value="{{$c->id}}">{{$c->name}}</option>@endforeach</select></div><div class="col-md-4 form-group"><label>Amount</label><input type="number" step=".0001" name="amount" class="form-control" required></div>
<div class="col-md-4 form-group"><label>Warehouse</label><select name="warehouse_id" class="form-control" required>@foreach($warehouses as $w)<option value="{{$w->id}}">{{$w->name}}</option>@endforeach</select></div><div class="col-md-4 form-group"><label>Cash/Bank Account</label><select name="account_id" class="form-control" required>@foreach($accounts as $a)<option value="{{$a->id}}">{{$a->name}}</option>@endforeach</select></div><div class="col-md-4 form-group"><label>Reference</label><input name="reference" class="form-control"></div><div class="col-md-12 form-group"><label>Purpose</label><input name="purpose" class="form-control" placeholder="Travel, accommodation, site expense..." required></div><div class="col-12"><button class="btn btn-primary">Post Employee Expense</button></div>
</div></form></div></div>
</div>

<div class="construction-form"><h4>Financial Custody / Employee Advance</h4><p class="text-muted">Issuance uses SalePro's Employee Advance Receivable account. Settlement can be recorded as supported project expense or cash returned.</p><form method="post" action="{{route('construction.employee-advances.store')}}">@csrf<div class="row">
<div class="col-md-3 form-group"><label>Employee / Custodian</label><select name="employee_id" class="form-control" required>@foreach($employees as $e)<option value="{{$e->id}}">{{$e->name}}</option>@endforeach</select></div><div class="col-md-3 form-group"><label>Project</label><select name="project_id" class="form-control"><option value="">General</option>@foreach($projects as $p)<option value="{{$p->id}}">{{$p->title}}</option>@endforeach</select></div><div class="col-md-2 form-group"><label>Date</label><input type="date" name="advance_date" value="{{date('Y-m-d')}}" class="form-control" required></div><div class="col-md-2 form-group"><label>Amount</label><input type="number" step=".0001" name="amount" class="form-control" required></div><div class="col-md-2 form-group"><label>Reference</label><input name="reference" class="form-control"></div>
<div class="col-md-3 form-group"><label>Warehouse</label><select name="warehouse_id" class="form-control" required>@foreach($warehouses as $w)<option value="{{$w->id}}">{{$w->name}}</option>@endforeach</select></div><div class="col-md-3 form-group"><label>Cash/Bank Account</label><select name="account_id" class="form-control" required>@foreach($accounts as $a)<option value="{{$a->id}}">{{$a->name}}</option>@endforeach</select></div><div class="col-md-4 form-group"><label>Notes</label><input name="notes" class="form-control"></div><div class="col-md-2 form-group d-flex align-items-end"><button class="btn btn-primary">Issue Advance</button></div>
</div></form></div>

<div class="construction-table table-responsive mb-4"><table class="table"><thead><tr><th>Date</th><th>Employee</th><th>Project</th><th>Issued</th><th>Expense Settled</th><th>Cash Returned</th><th>Outstanding</th><th>Status</th><th>Settlement</th></tr></thead><tbody>@foreach($advances as $a)<tr><td>{{$a->advance_date->format('Y-m-d')}}</td><td>{{$a->employee->name}}</td><td>{{$a->project->title??'General'}}</td><td>{{number_format($a->amount,2)}}</td><td>{{number_format($a->settled_expense_amount,2)}}</td><td>{{number_format($a->cash_returned_amount,2)}}</td><td><strong>{{number_format($a->outstanding_amount,2)}}</strong></td><td>{{$a->status}}</td><td>@if($a->status!=='settled')<form method="post" action="{{route('construction.employee-advances.settle',$a)}}">@csrf<div class="form-row"><div class="col"><select name="settlement_type" class="form-control form-control-sm"><option value="expense">Expense</option><option value="cash_return">Cash Return</option></select></div><div class="col"><input type="number" step=".0001" max="{{$a->outstanding_amount}}" name="amount" class="form-control form-control-sm" placeholder="Amount" required></div><div class="col"><input type="date" name="settlement_date" value="{{date('Y-m-d')}}" class="form-control form-control-sm" required></div><div class="col"><select name="cost_category_id" class="form-control form-control-sm"><option value="">Category</option>@foreach($categories as $c)<option value="{{$c->id}}">{{$c->name}}</option>@endforeach</select></div><div class="col"><select name="account_id" class="form-control form-control-sm"><option value="">Return account</option>@foreach($accounts as $ac)<option value="{{$ac->id}}">{{$ac->name}}</option>@endforeach</select></div><div class="col"><button class="btn btn-sm btn-secondary">Settle</button></div></div></form>@endif</td></tr>@endforeach</tbody></table></div>

<div class="row"><div class="col-lg-6"><div class="construction-table table-responsive"><h5>Recent Rewards</h5><table class="table table-sm"><thead><tr><th>Date</th><th>Employee</th><th>Project</th><th>Type</th><th>Amount</th><th>Status</th></tr></thead><tbody>@foreach($rewards as $r)<tr><td>{{$r->reward_date->format('Y-m-d')}}</td><td>{{$r->employee->name}}</td><td>{{$r->project->title??'Company'}}</td><td>{{$r->reward_type}}</td><td>{{number_format($r->amount,2)}}</td><td>{{$r->status}}</td></tr>@endforeach</tbody></table></div></div><div class="col-lg-6"><div class="construction-table table-responsive"><h5>Recent Employee Expenses</h5><table class="table table-sm"><thead><tr><th>Date</th><th>Employee</th><th>Project</th><th>Purpose</th><th>Amount</th><th>Accounting</th></tr></thead><tbody>@foreach($employeeExpenses as $x)<tr><td>{{$x->expense_date->format('Y-m-d')}}</td><td>{{$x->employee->name}}</td><td>{{$x->project->title??'General'}}</td><td>{{$x->purpose}}</td><td>{{number_format($x->amount,2)}}</td><td>{{$x->posting_status}}</td></tr>@endforeach</tbody></table></div></div></div>
</div>
@endsection
